<?php
/*
|--------------------------------------------------------------------------
| custom.module
|--------------------------------------------------------------------------|
| Arquivo é onde implementamos o layout que será enviado para o emails 
| usuário
| author Gianlucca Augusto <gianlucca.augusto@extreme.digital>
| version 1.0
| copyright Proderj 2022.
*/

/**
 * @file
 * Formulário
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_mail().
 */
function custom_mail($key, &$message, $params) {
  switch ($key) {
    case 'custom_notificacao':
      $message['from'] = \Drupal::config('system.site')->get('email');
      $site_name = \Drupal::config('system.site')->get('nome');

      $message['subject'] = $site_name . ": " . t('Novo Formulário Para Exposição Cultural');

      $message_body['nome'] = $params['message']['nome'];
      $message_body['email'] = $params['message']['email'];
      $message_body['telefone'] = $params['message']['telefone'];
      $message_body['msg'] = $params['message']['msg'];


      /**
       * Chama o template custom_notificacao
       */
      $message_theme_body = array(
        '#theme' => 'custom_notificacao',
        '#message_body' => $message_body,
       );
      
      $message_render = \Drupal::service('renderer')->render($message_theme_body);
      $message['body'][] = Html::escape($message_render);
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed;';
      break;

      case 'custom_protocolo':
        $message['from'] = \Drupal::config('system.site')->get('email');
        $site_name = \Drupal::config('system.site')->get('nome');
  
        $message['subject'] = $site_name . ": " . t('Confirmação do Formulário Para Exposição Cultural');
  
        $message_body['nome'] = $params['message']['nome'];
        $message_body['email'] = $params['message']['email'];
        $message_body['telefone'] = $params['message']['telefone'];
        $message_body['msg'] = $params['message']['msg'];
        
        /**
         * Chama o template custom_protocolo
         */
        $message_theme_body = array(
          '#theme' => 'custom_protocolo',
          '#message_body' => $message_body,
         );
        
        $message_render = \Drupal::service('renderer')->render($message_theme_body);
        $message['body'][] = Html::escape($message_render);
        $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed;';
        break;
  }
}

/**
 * Implements hook_theme().
 */
function custom_theme($existing, $type, $theme, $path) {
  return [
    'custom_notificacao' => [
      'variables' => ['message_body' => NULL],
    ],
    'custom_protocolo' => [
      'variables' => ['message_body' => NULL],
    ]
  ];
}
